# Change these first
owner: AMUS-SOFT # Your GitHub organization or username, where this repository lives
repo: amussoft-upptime # The name of this repository

sites:
  - name: FactuON auth API
    url: https://auth.factuon.com/
  - name: FactuON
    url: https://factuon.com
  - name: FactuON API
    url: https://api.factuon.com
  - name: EmployON
    url: https://employon.factuon.com
  - name: EmployON API
    url: https://api-employon.factuon.com
  - name: DeskON
    url: https://deskon.factuon.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /amussoft-upptime
  logoUrl: https://amussoft.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.7f6a680a.png&w=384&q=75
  name: AMUS SOFT Uptime Monitor
  introTitle: "This is an open-source uptime tracker and status page for AMUS SOFT services."
  introMessage: This status page delivers **real-time** uptime checks for AMUS SOFT's critical services, pulling data straight from our [GitHub repository](https://github.com/amussoft/uptime).
  navbar:
    - title: Status
      href: /
    - title: Contact Us
      href: https://amussoft.com/contactUs
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
